12.0 add product_pack
OCA/product-pack pull request #1
Opened 2019-09-19 14:47 UTC by ernestotejeda

Supersedes https://github.com/OCA/product-attribute/pull/498

Cc @tecnativa

2019-09-19 16:04 UTC, pedrobaeza commented
Please squash adjacent commits of the same author together to reduce a bit commit history.

Does the unfolding has been done? @legalsylvain what do you think about the unfolding of the `pack_price_type` field?

2019-09-26 17:59 UTC, rafaelbn approved these changes
:+1:  I think we should merge

2019-09-26 18:00 UTC, rafaelbn commented
https://github.com/OCA/product-attribute/pull/498

cc @jjscarafia @zaoral

2019-09-26 18:00 UTC, rafaelbn commented
@sergio-teruel please

2019-09-26 18:30 UTC, zaoral approved these changes

2019-09-30 14:02 UTC, ernestotejeda commented
I have done the unfolding of the pack_price_type field as @Yajo proposed here https://github.com/OCA/product-attribute/pull/498#issuecomment-532720466 but I left the *totalized* Pack Type option instead of the proposed *merged* option and I added to the readme that it can be added later

2019-09-30 15:15 UTC, pedrobaeza requested changes

2019-09-30 15:15 UTC, pedrobaeza commented on product_pack/__manifest__.py
> +    'summary': 'This module allows you to set a product as a product pack',
s/product pack/pack

2019-09-30 15:15 UTC, pedrobaeza commented on product_pack/views/product_template_views.xml
> +                                   attrs="{
Please put this in one line, or it will be seen on UI very ugly

2019-09-30 15:15 UTC, pedrobaeza commented on product_pack/migrations/12.0.1.0.0/pre-migration.py
> +                            THEN 'none_detailed'
General typo to be changed: `non_detailed`

2019-09-30 15:15 UTC, pedrobaeza commented on product_pack/migrations/12.0.1.0.0/pre-migration.py
> +                            THEN NULL
`assisted`

2019-09-30 15:15 UTC, pedrobaeza commented on product_pack/migrations/12.0.1.0.0/pre-migration.py
> +                            FALSE
Is with `then` or without?

2019-09-30 15:15 UTC, pedrobaeza commented on product_pack/migrations/12.0.1.0.0/pre-migration.py
> +         'product_template', 'char', False, 'product_template'),
s/char/selection

2019-09-30 15:15 UTC, pedrobaeza commented on product_pack/migrations/12.0.1.0.0/pre-migration.py
> +         'product_template', 'char', False, 'product_template'),
s/char/selection

2019-09-30 15:15 UTC, pedrobaeza commented on product_pack/migrations/12.0.1.0.0/pre-migration.py
> +    'sale_product_pack',
`stock_product_pack`

2019-09-30 16:33 UTC, ernestotejeda commented
Changes done

2019-10-01 06:05 UTC, pedrobaeza approved these changes

2019-10-01 06:05 UTC, pedrobaeza commented
/ocabot merge

2019-10-01 06:14 UTC, merged

2019-10-01 22:50 UTC, jjscarafia commented
:clap::clap::clap::clap: thanks for the great work to you all!