[13.0][MIG] product_pack
OCA/product-pack pull request #14
Opened 2020-04-09 20:18 UTC by jjscarafia

2020-04-10 09:55 UTC, pedrobaeza commented
Please see Travis status.

2020-04-10 10:40 UTC, jjscarafia commented
Hi @pedrobaeza thanks for the review. Can you help me a little bit? It seams to bre related to new pre-commit implementation but I didn't found documentation regarding this.
1. I've already run the "pre-commit run -a" as pointed [here](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#technical-method-to-migrate-a-module-from-120-to-130-branch)
2.Some lint errors I can fix and push again, but I don't understand [this one](https://travis-ci.com/github/OCA/product-pack/jobs/317894083#L321)


Thanks!

2020-04-10 18:20 UTC, jjscarafia commented
fixed @pedrobaeza 
thansk!

2020-04-11 18:20 UTC, pedrobaeza approved these changes

2020-04-15 13:54 UTC, ernestotejeda requested changes
Thanks @jjscarafia :+1: 

- Remove product_pack/migrations/12.0.1.0.0 folder

2020-04-15 13:54 UTC, ernestotejeda commented on product_pack/models/product_pack_line.py
> +                        _("You cannot set recursive packs.\n" "Product id: %s")
```suggestion
                        _("You cannot set recursive packs.\nProduct id: %s")
```

2020-04-15 13:54 UTC, ernestotejeda commented on product_pack/__manifest__.py
> +    "author": "NaN·tic, " "ADHOC SA, " "Tecnativa, " "Odoo Community Association (OCA)",
```suggestion
    "author": "NaN·tic, ADHOC SA, Tecnativa, Odoo Community Association (OCA)",
```
I know that black does things like this but they look a bit ugly and if we fixes it like that black won't change it again

2020-04-21 19:18 UTC, pedrobaeza commented
Please include #15

2020-04-29 14:35 UTC, pedrobaeza commented
Please include as well #18

2020-06-07 00:54 UTC, jjscarafia commented on product_pack/models/product_pack_line.py
> +                        _("You cannot set recursive packs.\n" "Product id: %s")
done @ernestotejeda thanks!

2020-06-07 00:57 UTC, jjscarafia commented
> Thanks @jjscarafia 
> 
> * Remove product_pack/migrations/12.0.1.0.0 folder

I're removed them but I don't get the point of doing it. We use odoo upgrade service and we often jump versions, for eg. we send odoo a v11 db and we get a v13 one, and we would like migration scriptf for v12 to be run while upgrading to v13

Any opinion regarding this @ernestotejeda @pedrobaeza ?

2020-06-07 01:15 UTC, jjscarafia commented
all the changes done. Thanks @pedrobaeza @ernestotejeda 

@pedrobaeza https://github.com/OCA/product-pack/pull/18/files will be considered on new pr for stock_product_pack

2020-06-07 02:31 UTC, jjscarafia commented
I've closed this PR and open a new one with same content because travis was red and I couldn't achive to re run it without a new PR.
https://github.com/OCA/product-pack/pull/22

2020-06-07 02:31 UTC, closed without merging