[18.0][MIG] product_pack: Migration to 18.0
OCA/product-pack pull request #189
Opened 2024-11-20 19:47 UTC by ALopez-Adhoc

2024-11-21 08:50 UTC, rousseldenis commented
/ocabot migration product_pack

2024-11-25 15:53 UTC, augusto-weiss commented
Hi @ALopez-Adhoc  thanks for migrate this module. Could you add the fix for this issue (#169) ? 
Some advantages are:
* Consistence between readme and behaivour (price defined by pack price + components price)
* Consistence price for detailled by components, totalized and non detailled packs
* If someone want to keep behaivour should set pack price = 0.0 in form view

2024-12-02 19:05 UTC, ALopez-Adhoc commented
@augusto-weiss Hi Augusto, thank you for the feedback. The mentioned changes have now been included. Please review them if there are ok checking the last commit. Any additional feedback is welcome.

2024-12-05 15:56 UTC, ALopez-Adhoc commented
@augusto-weiss Augusto, the commit where the changes requestes was rolled back due to inconsistencies with nested pricelist when creating sales orders. We are going to mantain the actual flow until the mentioned issue is corrected.

2024-12-12 14:53 UTC, nicolascol approved these changes
LGTM

2024-12-18 04:47 UTC, hspl-vegra approved these changes

2024-12-18 04:47 UTC, hspl-vegra commented
LGTM

2024-12-18 05:04 UTC, HeliconiaSolutions approved these changes
Functionally reviewed, LGTM.

2024-12-18 07:11 UTC, pedrobaeza reviewed
Is this having the latest changes in previous branches?

2024-12-18 07:11 UTC, pedrobaeza commented on product_pack/models/product_product.py
> -            # NOTE: This exception is to avoid adding the list price of the packs
Why removing this text?

2024-12-30 20:09 UTC, ALopez-Adhoc commented on product_pack/models/product_product.py
> -            # NOTE: This exception is to avoid adding the list price of the packs
My mistake. Already solved

2025-01-04 14:45 UTC, nicolascol commented
Hi @pedrobaeza 
Could you merge this PR or does it need changes?
Functionally it's OK

2025-01-04 14:54 UTC, pedrobaeza requested changes
And what about my previous comment about having all the changes in previous branches?

2025-01-04 14:54 UTC, pedrobaeza commented on product_pack/views/product_pack_line_views.xml
> +    <record id="product_pack_line_list" model="ir.ui.view">
Please don't rename XML-IDs for no gain in migrations. It only provokes possible headaches.

2025-01-06 16:32 UTC, ALopez-Adhoc commented on product_pack/views/product_pack_line_views.xml
> +    <record id="product_pack_line_list" model="ir.ui.view">
Duly corrected. Thanks for the review

2025-01-06 16:53 UTC, rousseldenis approved these changes

2025-01-06 18:55 UTC, ALopez-Adhoc commented
@pedrobaeza Excuse me for asking, what changes/branches are you referring to? This PR migrates from the most recent version from its start date, having all the changes included in the productive branch of version 17.0 to that date. I assume you are referring to the updates that have been from that date onwards in the 17.0 branch

2025-01-07 22:53 UTC, pedrobaeza commented
Yeah, that's it, and it's only for being sure.

2025-01-10 16:49 UTC, ALopez-Adhoc commented
@pedrobaeza This pr is up to date with the latest changes. Ready to merge if ok

2025-01-12 11:25 UTC, pedrobaeza commented
Isn't #198 applicable here?

2025-01-13 17:35 UTC, ALopez-Adhoc commented
@pedrobaeza Indeed, and it is included. The last push (commit hash: 8a749f9) introduced those changes.

2025-01-14 07:12 UTC, pedrobaeza approved these changes
/ocabot merge nobump

2025-01-14 07:16 UTC, merged