[18.0][MIG] sale_product_pack: Migration to 18
OCA/product-pack pull request #190
Opened 2024-11-21 22:04 UTC by ALopez-Adhoc

2024-11-22 08:12 UTC, rousseldenis commented
/ocabot migration sale_product_pack

2024-12-12 14:52 UTC, nicolascol approved these changes
LGTM

2025-01-04 14:47 UTC, nicolascol commented
Hi @pedrobaeza 
Could you merge?

2025-01-09 11:00 UTC, marielejeune requested changes

2025-01-09 11:00 UTC, marielejeune commented on sale_product_pack/views/product_pack_line_views.xml
> +        <field name="inherit_id" ref="product_pack.product_pack_line_list" />
The inherited view xmlid didn't change in `product_pack` addon, it is still `product_pack.product_pack_line_tree`

2025-01-09 11:00 UTC, marielejeune commented on sale_product_pack/views/product_pack_line_views.xml
> +    <record id="product_pack_line_list" model="ir.ui.view">
I'd prefer not changing view xmlids, it can cause compatibilities problems.
What do you think @pedrobaeza ? What's the strategy about all these "tree" changed by "list" ?

2025-01-09 11:04 UTC, pedrobaeza commented on sale_product_pack/views/product_pack_line_views.xml
> +    <record id="product_pack_line_list" model="ir.ui.view">
To not change XML-IDs. You have to change the tag, not the XML-ID

2025-01-09 12:46 UTC, marielejeune commented
Hi, one more comment:
Button "Locked" on a child sale order line (pack component) is not working. Here is the error.

![image](https://github.com/user-attachments/assets/94b107a4-46c0-4168-ac04-8b311c5cf707)

2025-01-09 18:48 UTC, ALopez-Adhoc commented on sale_product_pack/views/product_pack_line_views.xml
> +        <field name="inherit_id" ref="product_pack.product_pack_line_list" />
Solved. Rolled back to it's old id

2025-01-09 18:48 UTC, ALopez-Adhoc commented on sale_product_pack/views/product_pack_line_views.xml
> +    <record id="product_pack_line_list" model="ir.ui.view">
Solved. Rolled back to it's old id

2025-01-09 19:37 UTC, ALopez-Adhoc commented
@marielejeune Fixed the error with the Locked button.

2025-01-17 13:50 UTC, matiasperalta1 approved these changes
LGTM

2025-01-17 13:52 UTC, matiasperalta1 commented
@pedrobaeza Hi! Everything seems ok. Could we merge it?

2025-01-17 14:16 UTC, pedrobaeza approved these changes
/ocabot merge nobump

2025-01-17 14:35 UTC, merged