12.0 add stock_product_pack
OCA/product-pack pull request #3
Opened 2019-09-19 17:07 UTC by ernestotejeda

Cc @Tecnativa

2019-09-30 14:28 UTC, ernestotejeda commented
Ready to review

2019-10-15 21:13 UTC, zeroheure requested changes
stock_product_pack/readme/DESCRIPTION.rst
> This module allows you to get the right available *On Hand* and *Forecasted*
> quantities of the packs.

This module allows you to get *On Hand* and *Forecasted* values calculated from components of the pack.

2019-10-15 21:18 UTC, zeroheure commented on stock_product_pack/readme/CONFIGURE.rst
> +#. Set type of product pack.
Wrong order
#. Go to *Inventory -> Master Data -> Product*, create a product and check
   *Is Pack?* field then set *Pack Type* and *Pack component price*.
#. Choose products to include in the pack.

2019-10-15 21:25 UTC, zeroheure commented on stock_product_pack/readme/CONFIGURE.rst
> +
This should be in USAGE.rst

2019-10-15 21:25 UTC, zeroheure commented on stock_product_pack/readme/DESCRIPTION.rst
> +quantities of the packs.
Bad english 
_This module allows you to get On Hand and Forecasted values calculated from components of the pack._

2019-10-22 15:56 UTC, pedrobaeza approved these changes
Let's merge full pack of the pack modules :yum: for having the whole picture. We can bugfixing later with everything in place.

2019-10-22 15:57 UTC, merged