[13.0] [IMP] stock_product_pack: Show the stock values for products pack.
OCA/product-pack pull request #38
Opened 2021-03-31 14:12 UTC by nicomacr

If the product pack is not a type "product" the stock values are not showed in the tree, form and kanban views.
Now after this PR we show for all the types of products if it's a pack the stock values.

2021-09-02 07:24 UTC, chienandalu reviewed
Rebase and solve conflicts. Also a readme section explaining the feature would be welcome

2021-09-13 02:19 UTC, jcbr87 commented
@nicomacr I have tested the change and it is functional.

2022-02-08 15:00 UTC, Meisolsson requested changes
Tested on Odoo version 13: Works as intended.

Small formatting thing from the guidelines.

2022-02-08 15:00 UTC, Meisolsson commented on stock_product_pack/views/product_product_views.xml
> +    <record model="ir.ui.view" id="product_form_view_procurement_button">
Small thing, according to the OCA Guidelines under section 2.1 i states "Place id attribute before model". So this line and the other it should be switched.

```suggestion
    <record id="product_form_view_procurement_button" model="ir.ui.view">
```

2022-02-08 15:00 UTC, Meisolsson commented on stock_product_pack/views/product_product_views.xml
> +    <record model="ir.ui.view" id="view_stock_product_tree">
See earlier comment.

2022-02-08 15:00 UTC, Meisolsson commented on stock_product_pack/views/product_template_views.xml
> +    <record model="ir.ui.view" id="product_template_form_view_procurement_button">
See earlier comment.

2022-02-08 15:00 UTC, Meisolsson commented on stock_product_pack/views/product_template_views.xml
> +    <record model="ir.ui.view" id="product_template_kanban_stock_view">
See earlier comment.

2022-02-08 15:00 UTC, Meisolsson commented on stock_product_pack/views/product_template_views.xml
> +    <record model="ir.ui.view" id="view_stock_product_template_tree">
See earlier comment.

2022-02-08 18:33 UTC, nicomacr commented
@Meisolsson thanks for the review, changes suggested done!!

2022-02-09 11:56 UTC, Meisolsson approved these changes
Looks good after changes.

2022-06-12 16:16 UTC, pedrobaeza commented
@ernestotejeda can you please check?

2022-11-27 12:28 UTC, closed without merging